version: 1.0.{build}
image:
- Visual Studio 2017
clone_depth: 1

artifacts:
- path: jupyterq_windows-$(appveyor_repo_tag_name).zip
skip_non_tags: false
platform: x64

build_script:
- cmd: >-

    build\buildscript.bat

    tests\test.bat

after_build:
- cmd: >-

    build\package.bat

deploy:
 release: $(appveyor_repo_tag_name)
 provider: GitHub
 auth_token: $(GITHUB_APIKEY)
 on:
  appveyor_repo_tag: true
 

